steps:
  # install dependencies for unit testing
  - name: python:3.8-slim
    entrypoint: pip
    args: ["install", "-r", "requirements-test.txt", "--user"]

  # # Run tests on pipelines
  # - name: python:3.8-slim
  #   entrypoint: python3.8
  #   args: ["-m", "pytest", "-s", "pipelines/"]

  # Install dependencies for pipeline
  - name: python
    entrypoint: pip
    args: ["install", "-r", "pipelines/requirements.txt", "--user"]

  # Create Classic template for pipeline
  - name: python
    entrypoint: python
    args: ["-m", "pipelines/dfpipeline.py","--runner", "DataflowRunner","--secretManagerID", "authkey", "--gcsBucket", "load-data-into-bucket" ,"--url1", "https://cdn-api.co-vin.in/api/v2/appointment/centers/public/findByLatLong?lat=28.72&long=77.14"] #"--dataset", "csv_to_bq", "--tableID" ,"external_api_bq_data"]

  # # Running templates
  # - name: gcr.io/cloud-builders/gcloud
  #   args: ["dataflow", "jobs", "run", ""]