steps:
  # install dependencies for unit testing
  - name: python:3.8-slim
    entrypoint: pip
    args: ["install", "-r", "requirements-test.txt", "--user"]
  - name: gcr.io/cloud-builders/git
    entrypoint: /bin/bash
    args:
      - -c
      - |
        echo "saving newly added pipeline folders to new_pipelines"
        git diff --name-only HEAD~1 | awk -F "/*[^/]*/*$" '{ print ($1 == "" ? "." : $1); }' | sort | uniq