steps:
  # install dependencies for unit testing
  - name: python:3.8-slim
    entrypoint: pip
    args: ["install", "-r", "requirements-test.txt", "--user"]

  # # Run tests on pipelines
  # - name: python:3.8-slim
  #   entrypoint: python3.8
  #   args: ["-m", "pytest", "-s", "pipelines/"]

  # Install dependencies for pipeline
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  # Create Classic template for pipeline
  - name: python:3.6
    entrypoint: python
    args: ["-m", "dfpipeline","--runner DataflowRunner","--project", "q-gcp-8566-nj-dhs-22-08","--staging_location","gs://csv_to_bigquery_load/Staging","--temp_location", "gs://csv_to_bigquery_load/Temp", "--template_location","gs://csv_to_bigquery_load/Template/","--region us-central1"]
  # # Running templates
  # - name: gcr.io/cloud-builders/gcloud
  #   args: ["dataflow", "jobs", "run", ""]